### ISSUE TITLE
[BUG]: Replace absolute windows path to relative linux compatible path

### ISSUE THREAD

**Issue by C0re568** [Akkudoktor-EOS/EOS#182]
### Describe the issue:

There is a hardcoded absolute Windows path in src/akkudoktoreosserver/flask_server.py.

https://github.com/Akkudoktor-EOS/EOS/blob/cdf4d074e211cf689bf3b91063aba6d5bcd98047/src/akkudoktoreosserver/flask_server.py#L213C1-L214C1

This will not work on Linux or Docker.

--> Remove the debug output or replace it with a relative path that works on Linux.

### Reproduceable code example:

```python
Do a POST /optimize
```

### Error message:

```shell
172.27.0.1 - - [24/Oct/2024 21:38:32] "POST /optimize HTTP/1.1" 500 -

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__

    return self.wsgi_app(environ, start_response)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1476, in wsgi_app

    response = self.handle_exception(e)

               ^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app

    response = self.full_dispatch_request()

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request

    rv = self.handle_user_exception(e)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request

    rv = self.dispatch_request()

         ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/eos/akkudoktoreosserver/flask_server.py", line 212, in flask_optimize

    with open(

         ^^^^^

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\drbac\\OneDrive\\Dokumente\\PythonPojects\\EOS\\debug_output.txt'
```

### Version information:

main branch - last commit: [cdf4d07](https://github.com/Akkudoktor-EOS/EOS/commit/cdf4d074e211cf689bf3b91063aba6d5bcd98047)

Running in Docker

**Comment by NormannK** [comment]
thanks we have a PR #167 waiting to fix this
