### ISSUE TITLE
[BUG]: Docker startup fails after commit 3f67da1

### ISSUE THREAD

**Issue by XHalamaX** [Akkudoktor-EOS/EOS#278]
### Describe the issue:

The server is not starting via docker after commit 3f67da1

The commits before (43da234) are working

### Error message:

```shell
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/eos/akkudoktoreos/server/fastapi_server.py", line 50, in <module>
    config = load_config(working_dir, True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/eos/akkudoktoreos/config.py", line 248, in load_config
    _merge_and_update(config, update_outdated)
  File "/opt/eos/akkudoktoreos/config.py", line 222, in _merge_and_update
    with custom_config.open("w") as f_out:
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/pathlib.py", line 1013, in open
Custom directory provided. Setting working directory to: /opt/eos
Using configuration from: /opt/eos/EOS.config.json
Custom config /opt/eos/EOS.config.json is outdated...
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 30] Read-only file system: '/opt/eos/EOS.config.json'
```

### Version information:

```
cd /opt
sudo git clone https://github.com/Akkudoktor-EOS/EOS.git
cd /opt/EOS
sudo git reset --hard 3f67da1
sudo docker compose up -d
```

**Comment by Lasall** [comment]
As a temporary workaround you can set `read-only: false` in the `docker-compose.yml`.

**Comment by XHalamaX** [comment]
Hi @Lasall 
sorry I had different priorities in the last weeks. I would like to proceed with testing and understanding EOS but I think there is still or again this issue.

Commit "feature: Pv forecast refactoring" [1bf49c8](https://github.com/Akkudoktor-EOS/EOS/commit/1bf49c8c524ee2db966a9a771339c8141287d867) is working when I start it via docker :white_check_mark:
```
2025-01-23T19:48:07.422443996Z INFO:     Started server process [1]
2025-01-23T19:48:07.422512268Z INFO:     Waiting for application startup.
2025-01-23T19:48:07.423097608Z INFO:     Application startup complete.
2025-01-23T19:48:07.431600419Z INFO:     Uvicorn running on http://0.0.0.0:8503 (Press CTRL+C to quit)
```

After commit "workflow: docker-build upload to DockerHub" [b611151](https://github.com/Akkudoktor-EOS/EOS/commit/b6111517ca3775fffc6f63ace56f4f219806be8c) it is NOT working when I start it via docker :x:
```
2025-01-23T19:50:48.667550454Z /usr/local/lib/python3.12/site-packages/numpydantic/meta.py:66: UserWarning: ndarray.pyi stub file could not be generated: [Errno 30] Read-only file system: '/usr/local/lib/python3.12/site-packages/numpydantic/ndarray.pyi'
2025-01-23T19:50:48.667665598Z   warn(f"ndarray.pyi stub file could not be generated: {e}", stacklevel=1)
2025-01-23T19:50:51.032750262Z INFO:     Started server process [1]
2025-01-23T19:50:51.047812823Z INFO:     Waiting for application startup.
2025-01-23T19:50:51.047870435Z INFO:     Application startup complete.
2025-01-23T19:50:51.049302940Z INFO:     Uvicorn running on http://localhost:8503 (Press CTRL+C to quit)
```

**Comment by Lasall** [comment]
The log doesn't show any errors, do you mean the warning? eos should function just fine. Can you access the the endpoints (e.g. go to localhost:8503/docs)

**Comment by XHalamaX** [comment]
/docs was not available. Also optimize or so is not responding

Are there any other ways of checking the logs?

**Comment by Lasall** [comment]
The current main-Image seems to be broken, I'll work on a fix.
